### ISSUE TITLE
segfault to investigate

### ISSUE THREAD

**Issue by soratidus999** [soratidus999/AuroraMonitor#1]
gdb) file auroramon
Reading symbols from auroramon...
(gdb) run
Starting program: /home/joel/AuroraMonitor/src/auroramon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00031ac4 in GraphPanel::ReadEnergyFile (this=0x2d6458, inv=0, filename=..., control=0, date_str=0x0) at chart.cpp:1826
1826	                                dsp_data[inv][column_dsp[column]][timeix] = (int)((d.extra[column-6] + ptype->addition) * ptype->multiply);
(gdb)

**Comment by soratidus999** [comment]
possible cause
#1  0x00021abc in OpenLogFiles (create=-1, control=1) at auroramonMain.cpp:671
#2  0x000504a4 in UpdatePowerData (fname10sec=...) at comms.cpp:1902
#3  0x000505cc in Mainframe::OnInverterEvent (this=0xef1b0, event=...) at comms.cpp:1922
